// Generated by @tanstack/router-plugin. Do not edit.
//
// This stub exists so `tsc` and `vite` can resolve `routeTree.gen.ts` before
// the plugin has had a chance to run. As soon as `vite` (or `vite build`)
// starts, the plugin rewrites this file with the real route tree synthesised
// from `src/app/router/routes/*`.
//
// We intentionally import the actual route definitions here so the stub still
// renders a working app even if the plugin has not yet executed.

import { rootRoute } from './routes/__root.js';
import { indexRoute } from './routes/index.js';
import { loginRoute } from './routes/login.js';
import { postsRoute } from './routes/posts.js';

export const routeTree = rootRoute.addChildren([indexRoute, loginRoute, postsRoute]);
