import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    users: 'src/users.ts',
    auth: 'src/auth.ts',
    casl: 'src/casl.ts',
    errors: 'src/errors.ts',
    routes: 'src/routes.ts',
    openapi: 'src/openapi.ts',
    organisations: 'src/organisations.ts',
    'audit-log': 'src/audit-log.ts',
    memberships: 'src/memberships.ts',
    profile: 'src/profile.ts',
    'belt-systems': 'src/belt-systems.ts',
    ranks: 'src/ranks.ts',
    'shogo-titles': 'src/shogo-titles.ts',
    'rank-history': 'src/rank-history.ts',
    labels: 'src/labels.ts',
    'feature-flags': 'src/feature-flags.ts',
    'classification-category': 'src/classification-category.ts',
    techniques: 'src/techniques.ts',
    patterns: 'src/patterns.ts',
  },
  format: ['esm', 'cjs'],
  dts: true,
  clean: true,
  sourcemap: true,
  target: 'es2022',
  splitting: false,
  treeshake: true,
  outDir: 'dist',
});
